# Generated by Django 5.0.7 on 2024-08-08 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
